# Generated by Django 4.0.4 on 2022-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('product_id', models.TextField()),
                ('ratings', models.TextField()),
                ('timestamp', models.TextField()),
            ],
        ),
    ]
